/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ActivationContract {
  export type LicenseInfoStruct = {
    isActive: boolean;
    hardwareHash: BytesLike;
    activatedAt: BigNumberish;
  };

  export type LicenseInfoStructOutput = [
    isActive: boolean,
    hardwareHash: string,
    activatedAt: bigint
  ] & { isActive: boolean; hardwareHash: string; activatedAt: bigint };
}

export interface ActivationContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activateLicense"
      | "deactivateLicense"
      | "gameToken"
      | "getLicense"
      | "isActive"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activateLicense",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateLicense",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gameToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getLicense",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isActive",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activateLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLicense", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
}

export interface ActivationContract extends BaseContract {
  connect(runner?: ContractRunner | null): ActivationContract;
  waitForDeployment(): Promise<this>;

  interface: ActivationContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activateLicense: TypedContractMethod<
    [tokenId: BigNumberish, machineHash: BytesLike],
    [void],
    "nonpayable"
  >;

  deactivateLicense: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  gameToken: TypedContractMethod<[], [string], "view">;

  getLicense: TypedContractMethod<
    [owner: AddressLike, tokenId: BigNumberish],
    [ActivationContract.LicenseInfoStructOutput],
    "view"
  >;

  isActive: TypedContractMethod<
    [owner: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activateLicense"
  ): TypedContractMethod<
    [tokenId: BigNumberish, machineHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateLicense"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gameToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLicense"
  ): TypedContractMethod<
    [owner: AddressLike, tokenId: BigNumberish],
    [ActivationContract.LicenseInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<
    [owner: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  filters: {};
}
