/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GamePassInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MONTH"
      | "expiryOf"
      | "gameStore"
      | "keyCoin"
      | "registerPass"
      | "subscribe"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PassSubscribed"): EventFragment;

  encodeFunctionData(functionFragment: "MONTH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "expiryOf",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gameStore", values?: undefined): string;
  encodeFunctionData(functionFragment: "keyCoin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerPass",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "MONTH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "expiryOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gameStore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keyCoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerPass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
}

export namespace PassSubscribedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    subscriber: AddressLike,
    months: BigNumberish,
    newExpiry: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    subscriber: string,
    months: bigint,
    newExpiry: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    subscriber: string;
    months: bigint;
    newExpiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GamePass extends BaseContract {
  connect(runner?: ContractRunner | null): GamePass;
  waitForDeployment(): Promise<this>;

  interface: GamePassInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MONTH: TypedContractMethod<[], [bigint], "view">;

  expiryOf: TypedContractMethod<
    [subscriber: AddressLike, gameId: BigNumberish],
    [bigint],
    "view"
  >;

  gameStore: TypedContractMethod<[], [string], "view">;

  keyCoin: TypedContractMethod<[], [string], "view">;

  registerPass: TypedContractMethod<
    [gameId: BigNumberish, monthlyPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  subscribe: TypedContractMethod<
    [gameId: BigNumberish, months: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MONTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "expiryOf"
  ): TypedContractMethod<
    [subscriber: AddressLike, gameId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "gameStore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "keyCoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerPass"
  ): TypedContractMethod<
    [gameId: BigNumberish, monthlyPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<
    [gameId: BigNumberish, months: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PassSubscribed"
  ): TypedContractEvent<
    PassSubscribedEvent.InputTuple,
    PassSubscribedEvent.OutputTuple,
    PassSubscribedEvent.OutputObject
  >;

  filters: {
    "PassSubscribed(uint256,address,uint256,uint256)": TypedContractEvent<
      PassSubscribedEvent.InputTuple,
      PassSubscribedEvent.OutputTuple,
      PassSubscribedEvent.OutputObject
    >;
    PassSubscribed: TypedContractEvent<
      PassSubscribedEvent.InputTuple,
      PassSubscribedEvent.OutputTuple,
      PassSubscribedEvent.OutputObject
    >;
  };
}
