/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ActivationContract } from "./ActivationContract";
export type { GamePass } from "./GamePass";
export type { GameStore } from "./GameStore";
export type { GameToken } from "./GameToken";
export type { IActivation } from "./IActivation";
export type { KeyCoin } from "./KeyCoin";
export type { Marketplace } from "./Marketplace";
