/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IActivation,
  IActivationInterface,
} from "../../contracts/IActivation";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "isActive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IActivation__factory {
  static readonly abi = _abi;
  static createInterface(): IActivationInterface {
    return new Interface(_abi) as IActivationInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IActivation {
    return new Contract(address, _abi, runner) as unknown as IActivation;
  }
}
