/**
 * Contract configuration loader
 *
 * Loads ABI from src/abi/ and deployed addresses from environment variables.
 * Used by useContract() hook to create ethers.Contract instances.
 *
 * After deploying contracts, set addresses in frontend/.env.local:
 *   NEXT_PUBLIC_KEYCOIN_ADDRESS=0x...
 *   NEXT_PUBLIC_GAMETOKEN_ADDRESS=0x...
 *   etc.
 */

import type { ContractName } from "./constants";

// ABI imports — these files are generated by `npm run copy-abi` in blockchain/
// They will be empty until contracts are compiled.
// import KeyCoinABI from "@/abi/KeyCoin.json";
// import GameTokenABI from "@/abi/GameToken.json";
// import GameStoreABI from "@/abi/GameStore.json";
// import ActivationContractABI from "@/abi/ActivationContract.json";
// import MarketplaceABI from "@/abi/Marketplace.json";
// import GamePassABI from "@/abi/GamePass.json";

interface ContractConfig {
  abi: unknown[];
  address: string;
}

/**
 * Returns the ABI and deployed address for a given contract.
 * Throws if the address is not configured (contract not deployed yet).
 */
export function getContractConfig(name: ContractName): ContractConfig {
  const addressMap: Record<ContractName, string | undefined> = {
    KeyCoin: process.env.NEXT_PUBLIC_KEYCOIN_ADDRESS,
    GameToken: process.env.NEXT_PUBLIC_GAMETOKEN_ADDRESS,
    GameStore: process.env.NEXT_PUBLIC_GAMESTORE_ADDRESS,
    ActivationContract: process.env.NEXT_PUBLIC_ACTIVATION_ADDRESS,
    Marketplace: process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS,
    GamePass: process.env.NEXT_PUBLIC_GAMEPASS_ADDRESS,
  };

  const address = addressMap[name];
  if (!address) {
    throw new Error(
      `[contracts] ${name} address not configured. ` +
        `Set NEXT_PUBLIC_${name.toUpperCase()}_ADDRESS in .env.local after deploying.`
    );
  }

  // TODO: Uncomment ABI imports above after contracts are compiled
  const abiMap: Record<ContractName, unknown[]> = {
    KeyCoin: [],       // KeyCoinABI,
    GameToken: [],     // GameTokenABI,
    GameStore: [],     // GameStoreABI,
    ActivationContract: [], // ActivationContractABI,
    Marketplace: [],   // MarketplaceABI,
    GamePass: [],      // GamePassABI,
  };

  return { abi: abiMap[name], address };
}
